name: flutter_mapbox_turn_by_turn
description: Turn By Turn Navigation for Your Flutter Application
version: 0.1.0
homepage: https://github.com/AnnonAU/flutter_mapbox_turn_by_turn

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=3.0.4"

dependencies:
  device_info_plus: ^4.0.0
  flutter:
    sdk: flutter
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: au.com.annon.flutter_mapbox_turn_by_turn
        pluginClass: FlutterMapboxTurnByTurnPlugin
      ios:
        pluginClass: FlutterMapboxTurnByTurnPlugin
